#application 
app:
  name: teston

spring:
  profiles:
    active: prd

DATA_HOME: /opt/thoughtware/teston

#io.thoughtware.teston.web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020


#dfs 
dfs:
  server:
    enable: true
    mode: server
    port: 4010
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4010
    bucket: ${app.name}

#dcs 
dcs:
  server:
    enabled: true
    port: 5010
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url:  http://bac.teston.thoughtware.cn

eas:
  embbed:
    enable: false
  address:  http://bac.eas.houghtware.cn

postgresql:
  database: teston
  embbed:
    enable: false
#  db:
#    port: 5432
#    username: postgres
#    password: darth2020
#    address: ${DATA_HOME}/postgresql

teston-agent:
  embbed:
    enable: true
  chromedriver:
    path: /opt/chrome/chromedriver/chromedriver
  chrome:
    path: /opt/chrome/chrome/chrome


file:
  path:
homes:
  address: http://192.168.10.7


backups:
  dir:  /data/teston
  time: 0 0 2 * * ?
