#application io.tiklab.teston.config
app:
  name: teston
spring:
  profiles:
    active: dev

DATA_HOME: ${user.home}/tiklab/${app.name}

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs
dcs:
  server:
    enabled: true
    port: 5010
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200
#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}


eas:
  embbed:
    enable: true
#  address: http://eas.dev.tiklab.net
#  web:
#    address: http://eas.local.tiklab.net

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://192.168.10.16:3000

teston-agent:
  embbed:
    enable: true

postin:
  enable: false
  scan:
    package: io.tiklab.teston
  report:
    workspaceId: f5b82a695903
    server: http://192.168.10.3:8090

file:
  path:
homes:
  address: http://192.168.10.7


backups:
  dir:  /data/teston
  time: 0 0 2 * * ?

postgresql:
  type: local
