#application io.thoughtware.teston.config
app:
  name: teston
spring:
  profiles:
    active: dev

DATA_HOME: ${user.home}/thoughtware/${app.name}

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs
dcs:
  server:
    enabled: true
    port: 5010
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200
#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}


eas:
  embbed:
    enable: false
  address: http://192.168.10.10:8080
  web:
    address: http://192.168.10.10:8080


#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://192.168.10.16:3000

teston-agent:
  embbed:
    enable: true
  chromedriver:
    path: D:\a-dk-sever\chrome\chromedriver.exe
  chrome:
    path: D:\a-dk-sever\chrome\chrome-win\chrome.exe
  appium:
    server: 127.0.0.1
    port: 4723


postin:
  enable: false
  scan:
    package: io.thoughtware.teston
  report:
    workspaceId: fae36fc39946
    server: http://192.168.10.21:8090

file:
  path:
homes:
  address: http://192.168.10.7


backups:
  dir:  /data/teston
  time: 0 0 2 * * ?

postgresql:
  type: local
