#application 
app:
  name: teston

spring:
  profiles:
    active: prd

DATA_HOME: /opt/tiklab/teston

#web 
server:
  port: 8080

#dal 
#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.12.1.16:3306/tiklab_teston?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: darth2020
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020


#dfs 
dfs:
  server:
    enable: true
    mode: server
    port: 4010
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4010
    bucket: ${app.name}

#dcs 
dcs:
  server:
    enabled: false
    mode: server
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    bucket: ${app.name}

#dss 
dss:
  server:
    enable: false
    mode: server
    port: 6010
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6010
    bucket: ${app.name}

#integration
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

application: teston

file:
  path: http://file.test.tiklab.net

base:
  url:  http://bac.teston.tiklab.net

eas:
  embbed:
    enable: false
  address:  http://bac.eas.tiklab.net

mysql:
  database: tiklab_teston
  embbed:
    enable: false

teston-agent:
  embbed:
    enable: true