#application io.tiklab.teston.config
app:
  name: tiklab-teston

spring:
  profiles:
    active: prd

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web io.tiklab.teston.config
server:
  port: 8080

#dal io.tiklab.teston.config
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.12.1.16:3306/tiklab_teston?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020


#dfs io.tiklab.teston.config
dfs:
  server:
    enable: false
    mode: server
    port: 4010
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4010
    bucket: ${app.name}

#dcs io.tiklab.teston.config
dcs:
  server:
    enable: false
    mode: server
    port: 5010
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5010
    bucket: ${app.name}

#dss io.tiklab.teston.config
dss:
  server:
    enable: false
    mode: server
    port: 6010
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6010
    bucket: ${app.name}

#integration
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${PROJECT_HOME}/plugin

#licences
licences:
  path: ${PROJECT_HOME}/licences

application: teston

file:
  path: http://file.test.tiklab.net

base:
  url: bac.teston.tiklab.net

eas:
  embbed:
    enable: false
  address: bac.eas.tiklab.net

mysql:
  database: tiklab_teston
  embbed:
    enable: false

teston-agent:
  embbed:
    enable: true