#application io.tiklab.teston.config
app:
  name: teston

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

DATA_HOME: ${user.home}/tiklab/${app.name}

#web io.tiklab.teston.config
server:
  port: 8080

#dal io.tiklab.teston.config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020


#dfs io.tiklab.teston.config
dfs:
  server:
    enable: false
    mode: server
    port: 4010
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4010
    bucket: ${app.name}

#dcs io.tiklab.teston.config
dcs:
  server:
    enable: false
    mode: server
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    bucket: ${app.name}

#dss io.tiklab.teston.config
dss:
  server:
    enable: false
    mode: server
    port: 6010
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6010
    bucket: ${app.name}

#integration io.tiklab.teston.config
homes:
  address: http://172.11.1.11:8080

#plugin io.tiklab.teston.config
plugin:
  path: ${DATA_HOME}/plugin

#licences io.tiklab.teston.config
licences:
  path: ${DATA_HOME}/licences

application: teston

file:
  path: http://file.tiklab.net

base:
  url: http://

eas:
  embbed:
    enable: true
#  address:

postgresql:
  database: tiklab_teston
  embbed:
    enable: true