#application
app:
  name: teston
spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

DATA_HOME: opt/tiklab/teston

#web 
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs
dcs:
  server:
    enable: false
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200

eas:
  embbed:
    enable: true
#  address:

#integration 
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

application: teston

file:
  path: http://file.tiklab.net

base:
  url: http://
