#application
app:
  name: teston
spring:
  profiles:
    active: demo

DATA_HOME: ${user.home}/tiklab/${app.name}

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_teston?stringtype=unspecified
  username: postgres
  password: darth2020

#dfs
dfs:
  server:
    enable: false
    mode: server
    port: 4010
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4010
    bucket: ${app.name}

#dcs
dcs:
  server:
    enable: false
    mode: server
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    bucket: ${app.name}

#dss
dss:
  server:
    enable: false
    mode: server
    port: 6010
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6010
    bucket: ${app.name}

#name
application: teston

#homes
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences



file:
  path: http://file.demo.tiklab.net

base:
  url: http://teston-ce.demo.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

postgresql:
  database: tiklab_teston
  embbed:
    enable: false

teston-agent:
  embbed:
    enable: true