#application
app:
  name: teston
spring:
  profiles:
    active: demo

DATA_HOME:  /opt/tiklab/teston

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/teston?stringtype=unspecified
  username: postgres
  password: darth2020


#dcs
dcs:
  server:
    enabled: false
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200

#name
application: teston

#homes
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

file:
  path: http://file.demo.tiklab.net

base:
  url: http://teston-ce.demo.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

postgresql:
  database: teston
  embbed:
    enable: true
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

teston-agent:
  embbed:
    enable: true