#application
app:
  name: teston
spring:
  profiles:
    active: demo

DATA_HOME:  /opt/tiklab/teston

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/teston?stringtype=unspecified
  username: postgres
  password: darth2020


#dcs
dcs:
  server:
    enabled: true
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200
#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}


#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://teston-ce.demo.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

postgresql:
  database: teston
  embbed:
    enable: true
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

teston-agent:
  embbed:
    enable: true


file:
  path:
homes:
  address: http://192.168.10.7


backups:
  dir:  /data/teston
  time: 0 0 2 * * ?
